# Generated by Django 3.2.4 on 2021-06-26 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('FROZEN_FOOD', 'Frozen items'), ('FRUITS', 'Fruits'), ('VEGETABLE', 'Vegetable'), ('COOKING_ITEMS', 'Cooking items'), ('CANNED_GOODS', 'Canned goods'), ('SNACKS', 'Snacks items'), ('CEREAL', 'Cereals'), ('PERSONAL_CARE', 'Personal care items'), ('HOUSEHOLD_ITEMS', 'Day to day items'), ('MASALA', 'Masala items'), ('COOL_DRINKS', 'Cool drinks'), ('ELECTRONICS', 'Electronic goods'), ('OTHERS', 'Other items')], default='OTHERS', max_length=30)),
                ('cost_prize', models.FloatField()),
                ('expiry_date', models.DateField(default=datetime.date(2048, 11, 11))),
                ('count', models.IntegerField(default=1)),
                ('quantity', models.FloatField()),
                ('quantity_type', models.CharField(choices=[('NO_OF_ITEMS', 'Number of item'), ('GRAM', 'Grams'), ('KILO_GRAM', 'Kilo grams'), ('LITRE', 'Litre'), ('MILLI_LITRE', 'Milli litre')], default='NO_OF_ITEMS', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.FloatField()),
                ('profit', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('product_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_entry')),
            ],
        ),
    ]
