# Generated by Django 3.2.4 on 2021-06-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Entry',
            new_name='ProductEntry',
        ),
        migrations.RenameModel(
            old_name='Product_Exit',
            new_name='ProductExit',
        ),
    ]
