# Generated by Django 3.2.4 on 2021-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210626_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='quantity_type',
        ),
        migrations.AddField(
            model_name='productentry',
            name='specs',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
