# Generated by Django 3.2.4 on 2021-06-27 10:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210626_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2048, 11, 12)),
        ),
        migrations.AlterField(
            model_name='productexit',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
