# Generated by Django 3.2.4 on 2021-06-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210627_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='cost_prize',
            new_name='cost_price',
        ),
    ]
