# Generated by Django 3.2.4 on 2021-06-27 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_rename_cost_prize_productentry_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productexit',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
